version: '2.2'

volumes:
  front_build:

services:
  auth:
    build:
      context: .
      dockerfile: docker_config/authentication/Dockerfile
    env_file:
      - ./docker_config/db_pass.env
      - ./docker_config/authentication/env.env
    restart: on-failure
    pids_limit: 100
    cpus: 0.25
    mem_limit: 500M

  player_internal:
    build:
      context: .
      dockerfile: docker_config/player/internal/Dockerfile
    volumes:
      - ./docker_volumes/anime:/anime
    restart: on-failure
    pids_limit: 100
    cpus: 0.50
    mem_limit: 500M

  player_api:
    build:
      context: .
      dockerfile: docker_config/player/api/Dockerfile
    env_file:
      - ./docker_config/db_pass.env
    volumes:
      - ./docker_volumes/anime:/anime:ro
    restart: on-failure
    pids_limit: 100
    cpus: 0.50
    mem_limit: 500M

  chat:
    build:
      context: .
      dockerfile: docker_config/chat/Dockerfile
    env_file:
      - ./docker_config/chat/env.env
      - ./docker_config/db_pass.env
    restart: on-failure
    pids_limit: 100
    cpus: 0.25
    mem_limit: 500M

  anidb:
    build:
      context: .
      dockerfile: docker_config/anidb/Dockerfile
    env_file:
      - ./docker_config/anidb/env.env
      - ./docker_config/db_pass.env
    volumes:
      - ./docker_volumes/anidb:/db
    restart: on-failure
    pids_limit: 100
    cpus: 0.25
    mem_limit: 500M


  nginx:
    image: nginx:1.15.9-alpine
    volumes:
      - ./docker_config/nginx/conf:/etc/nginx/conf.d:ro
      - ./docker_config/nginx/proxy_params:/etc/nginx/proxy_params:ro
      - front_build:/front_build:ro
    ports:
      - "8000:80"
    restart: on-failure
    pids_limit: 100
    cpus: 0.50
    mem_limit: 200M

  front:
    build:
      context: .
      dockerfile: docker_config/front/Dockerfile
    volumes:
      - front_build:/front_build
    restart: on-failure

  postgres:
    image: postgres:10.8-alpine
    volumes:
      - ./docker_volumes/postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./docker_config/db_pass.env
    restart: on-failure

  redis:
    image: redis:5.0.5-alpine
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    sysctls:
      net.core.somaxconn: 1024
    env_file:
      - ./docker_config/db_pass.env
    restart: on-failure

  mongo:
    image: mongo:4
    volumes:
      - ./docker_volumes/mongodb:/data/db
    env_file:
      - ./docker_config/db_pass.env
    restart: on-failure
    pids_limit: 100
    cpus: 0.5
    mem_limit: 500M
