version: '2.4'

volumes:
  front_build:

services:
  auth:
    build:
      context: .
      dockerfile: docker_config/authentication/Dockerfile
    env_file:
      - ./docker_config/db_pass.env
      - ./docker_config/authentication/env.env

  player_internal:
    build:
      context: .
      dockerfile: docker_config/player/internal/Dockerfile
    restart: on-failure
    volumes:
      - ./docker_volumes/anime:/anime

  player_api:
    build:
      context: .
      dockerfile: docker_config/player/api/Dockerfile
    env_file:
      - ./docker_config/db_pass.env
    volumes:
      - ./docker_volumes/anime:/anime:ro

  nginx:
    image: nginx:1.15.9-alpine
    volumes:
      - ./docker_config/nginx/conf:/etc/nginx/conf.d:ro
      - ./docker_config/nginx/proxy_params:/etc/nginx/proxy_params:ro
      - front_build:/front_build:ro
    ports:
      - "8000:80"

  front:
    build:
      context: .
      dockerfile: docker_config/front/Dockerfile
    volumes:
      - ./front:/app

  postgres:
    image: postgres:10.8-alpine
    volumes:
      - ./docker_volumes/postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./docker_config/db_pass.env

  redis:
    image: redis:5.0.5-alpine
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    sysctls:
      net.core.somaxconn: 1024
    env_file:
      - ./docker_config/db_pass.env
